// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newService.proto

package grpc.newService;

public interface newResponseIntegerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:newResponseInteger)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 firstInteger = 2;</code>
   */
  int getFirstInteger();
}
